name: build
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Yarn dependencies using lockfile
        run: yarn --frozen-lockfile
      - name: Create a production build
        run: yarn build
